# Generated by Django 4.0.1 on 2022-02-11 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='user_id',
            new_name='user',
        ),
    ]
