# Generated by Django 4.0.1 on 2022-02-21 02:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activate',
            old_name='image',
            new_name='photo',
        ),
        migrations.AlterField(
            model_name='activate',
            name='title',
            field=models.CharField(db_index=True, max_length=100, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator('[ㄱ-힣]', message='한글을 입력해주세요.')]),
        ),
    ]
